// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6I6kkuoJT0p3_eoaB30CQGoLJlw8P_Is',
    appId: '1:458555653650:web:e3251849344b7c0b1ce2cb',
    messagingSenderId: '458555653650',
    projectId: 'suchullo-flt',
    authDomain: 'suchullo-flt.firebaseapp.com',
    storageBucket: 'suchullo-flt.appspot.com',
    measurementId: 'G-0Q2WRKLHTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9g6p1boUMvntZ8ph5Omm2CeKUNt4hQM',
    appId: '1:458555653650:android:23d09b659db653fc1ce2cb',
    messagingSenderId: '458555653650',
    projectId: 'suchullo-flt',
    storageBucket: 'suchullo-flt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-UpUPAKaySn-WN9lMrphZxQfdBaVc5jc',
    appId: '1:458555653650:ios:be115a1d3eeccdba1ce2cb',
    messagingSenderId: '458555653650',
    projectId: 'suchullo-flt',
    storageBucket: 'suchullo-flt.appspot.com',
    iosClientId: '458555653650-g8122oo4nru27d4tc059spd9iit7hdbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.scroadSellerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-UpUPAKaySn-WN9lMrphZxQfdBaVc5jc',
    appId: '1:458555653650:ios:be115a1d3eeccdba1ce2cb',
    messagingSenderId: '458555653650',
    projectId: 'suchullo-flt',
    storageBucket: 'suchullo-flt.appspot.com',
    iosClientId: '458555653650-g8122oo4nru27d4tc059spd9iit7hdbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.scroadSellerFlutter',
  );
}
